"""
core/report_generator.py

Medical Report Generator
WASKO Health AI

Generates PDF and DOCX consultation reports.
"""

from pathlib import Path
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from docx import Document

from config import REPORT_DIR


class ReportGenerator:

    def __init__(self):

        self.report_dir = Path(REPORT_DIR)

        self.report_dir.mkdir(
            parents=True,
            exist_ok=True
        )

    # -----------------------------------------------------
    # PDF
    # -----------------------------------------------------

    def generate_pdf(

        self,

        patient_name,

        language,

        conversation

    ):

        filename = (

            self.report_dir /

            f"{datetime.now():%Y%m%d_%H%M%S}.pdf"

        )

        styles = getSampleStyleSheet()

        doc = SimpleDocTemplate(str(filename))

        story = []

        story.append(

            Paragraph(

                "<b>WASKO Health AI</b>",

                styles["Title"]

            )

        )

        story.append(

            Paragraph(

                "Offline Medical Consultation Report",

                styles["Heading2"]

            )

        )

        story.append(Spacer(1, 20))

        story.append(

            Paragraph(

                f"<b>Patient:</b> {patient_name}",

                styles["Normal"]

            )

        )

        story.append(

            Paragraph(

                f"<b>Language:</b> {language}",

                styles["Normal"]

            )

        )

        story.append(

            Paragraph(

                f"<b>Date:</b> {datetime.now()}",

                styles["Normal"]

            )

        )

        story.append(Spacer(1, 15))

        for message in conversation:

            role = message["role"].title()

            content = message["content"]

            story.append(

                Paragraph(

                    f"<b>{role}</b>",

                    styles["Heading3"]

                )

            )

            story.append(

                Paragraph(

                    content,

                    styles["BodyText"]

                )

            )

            story.append(Spacer(1, 8))

        story.append(Spacer(1, 20))

        story.append(

            Paragraph(

                "<b>Medical Disclaimer</b>",

                styles["Heading2"]

            )

        )

        story.append(

            Paragraph(

                "This report is generated by WASKO Health AI. "
                "It is intended for informational purposes only "
                "and should not replace professional medical advice.",

                styles["BodyText"]

            )

        )

        doc.build(story)

        return filename

    # -----------------------------------------------------
    # DOCX
    # -----------------------------------------------------

    def generate_docx(

        self,

        patient_name,

        language,

        conversation

    ):

        filename = (

            self.report_dir /

            f"{datetime.now():%Y%m%d_%H%M%S}.docx"

        )

        doc = Document()

        doc.add_heading(

            "WASKO Health AI",

            0

        )

        doc.add_heading(

            "Offline Medical Consultation Report",

            level=1

        )

        doc.add_paragraph(

            f"Patient: {patient_name}"

        )

        doc.add_paragraph(

            f"Language: {language}"

        )

        doc.add_paragraph(

            f"Date: {datetime.now()}"

        )

        doc.add_heading(

            "Conversation",

            level=2

        )

        for message in conversation:

            doc.add_heading(

                message["role"].title(),

                level=3

            )

            doc.add_paragraph(

                message["content"]

            )

        doc.add_heading(

            "Medical Disclaimer",

            level=2

        )

        doc.add_paragraph(

            "This report is generated by WASKO Health AI "
            "and does not replace a licensed healthcare professional."

        )

        doc.save(filename)

        return filename


report_generator = ReportGenerator()
